#!/bin/bash

echo "=========================================="
echo "  REDIS CACHING TEST GUIDE"
echo "=========================================="
echo ""
echo "Cache Configuration:"
echo "  • Backend: Redis"
echo "  • TTL: 10 minutes"
echo "  • Cached Endpoints:"
echo "    - GET /api/products (all products)"
echo "    - GET /api/products/{id} (single product)"
echo ""

BASE_URL="http://localhost:9000"
AUTH="Authorization: Basic YWRtaW46QWRtaW5AMTIz"

echo "=========================================="
echo "TEST 1: First Request (Cache Miss)"
echo "=========================================="
echo "First request to /api/products/1 - will hit database"
echo ""
echo "Command:"
echo "curl -v '$BASE_URL/api/products/1' -H '$AUTH' 2>&1 | grep -E 'HTTP|Cache'"
echo ""
time curl -s -X GET "$BASE_URL/api/products/1" -H "$AUTH" > /dev/null
echo ""

echo "=========================================="
echo "TEST 2: Second Request (Cache Hit)"
echo "=========================================="
echo "Second request to /api/products/1 - will use cache (faster)"
echo ""
echo "Command:"
echo "curl -v '$BASE_URL/api/products/1' -H '$AUTH' 2>&1 | grep -E 'HTTP|Cache'"
echo ""
time curl -s -X GET "$BASE_URL/api/products/1" -H "$AUTH" > /dev/null
echo ""
echo "Note: Second request should be faster (served from Redis)"
echo ""

echo "=========================================="
echo "TEST 3: Verify Cache in Redis"
echo "=========================================="
echo "Connect to Redis and check cached keys:"
echo ""
echo "Command: docker exec redis redis-cli KEYS '*product*'"
echo ""
docker exec redis redis-cli KEYS '*product*' 2>/dev/null || echo "Redis not available in docker-compose"
echo ""

echo "=========================================="
echo "TEST 4: Check Cache TTL"
echo "=========================================="
echo "Check how long cache entries will live:"
echo ""
echo "Command: docker exec redis redis-cli TTL 'key_name'"
echo ""
echo "Expected: ~600 seconds (10 minutes)"
echo ""

echo "=========================================="
echo "TEST 5: Manual Cache Eviction"
echo "=========================================="
echo "Update a product - this evicts the cache:"
echo ""
echo "curl -X PUT '$BASE_URL/api/products/1' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H '$AUTH' \\"
echo "  -d '{\"name\":\"Updated\",\"description\":\"desc\",\"price\":999,\"stock\":5}'"
echo ""
echo "After update:"
echo "  1. Cache for /api/products/{id} is cleared"
echo "  2. Cache for /api/products (list) is cleared"
echo "  3. Next request will fetch fresh data from database"
echo ""

echo "=========================================="
echo "TEST 6: Performance Comparison"
echo "=========================================="
echo "Time 5 cached requests vs database query:"
echo ""
echo "5 Cached requests (should be ~50-100ms total):"
for i in {1..5}; do
  (time curl -s -X GET "$BASE_URL/api/products/1" -H "$AUTH" > /dev/null) 2>&1 | grep real
done
echo ""

echo "=========================================="
echo "TEST 7: View Redis Cache Data"
echo "=========================================="
echo "Get actual cached data from Redis:"
echo ""
echo "Command: docker exec redis redis-cli GET 'key_name'"
echo ""
echo "This will show the serialized product data cached in Redis"
echo ""

echo "=========================================="
echo "✅ CACHING IS WORKING IF:"
echo "=========================================="
echo "1. First request is slower (hits database)"
echo "2. Second request is faster (hits Redis cache)"
echo "3. 'docker exec redis redis-cli KEYS' shows product cache keys"
echo "4. After 10 minutes, cache auto-expires and resets"
echo "5. After update/delete, cache is cleared"
echo ""

echo "=========================================="
echo "🔍 REDIS CLI USEFUL COMMANDS"
echo "=========================================="
echo "docker exec redis redis-cli"
echo ""
echo "  KEYS '*'              - Show all cache keys"
echo "  KEYS '*product*'      - Show product caches"
echo "  GET 'key'             - Get cached data"
echo "  TTL 'key'             - See time-to-live"
echo "  FLUSHALL              - Clear all cache"
echo "  DBSIZE                - Show cache size"
echo "  MONITOR               - Watch live cache operations"
echo ""
